#!/bin/bash

version=1.0.8
real_portable_folder="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$real_portable_folder"
# Log file.
exec > >(tee log.txt) 2>&1
# Load common functions.
source bin/idevice-tool-kit/idevice-tool-kit

echo -e "A999 Activator (A9, iOS 9, 9 years later) v$version\n(C) 2025 Alex Free (3-BSD)\nhttps://github.com/alex-free/a999activator\n"

set_path

restore_signed_ios_for_device() {
    if [ $device = "iphone_6s_plus" ]; then
        restore_ipsw https://updates.cdn-apple.com/2025FallFCS/fullrestores/082-67213/C471E1B8-CB73-4E02-8A9E-39166CD4FD28/iPhone_5.5_15.8.5_19H394_Restore.ipsw
    elif [ $device = "iphone_6s" ]; then
        restore_ipsw https://updates.cdn-apple.com/2025FallFCS/fullrestores/082-67136/AC6F1095-935D-4892-9D11-84BE311843B4/iPhone_4.7_15.8.5_19H394_Restore.ipsw
    fi
    
    # Clean up.
    restore_signed_ios=false

    wait_for_normal_mode
    echo "iOS 15.8.5 has been restored! It will take some additional time for it to start up into Setup.app, please wait..."
 
    did_you_follow_instructions
}

restore_ios_10_2_1_for_device() {
    # Needed for iOS 9.x
    if [ $device = "iphone_6s" ]; then
        restore_ipsw http://appldnld.apple.com/ios10.2.1/031-96803-20170112-6151BFBE-D81D-11E6-8553-F701D55B5B9D/iPhone_4.7_10.2.1_14D27_Restore.ipsw
    elif [ $device = "iphone_6s_plus" ]; then
        restore_ipsw http://appldnld.apple.com/ios10.2.1/031-96800-20170112-6151CD56-D81D-11E6-A447-F501D55B5B9D/iPhone_5.5_10.2.1_14D27_Restore.ipsw
    fi
}

iproxy_start() {
    iproxy 6414 22 > /dev/null 2>&1 &
}

iproxy_kill() {
    killall iproxy > /dev/null 2>&1
}

did_you_follow_instructions() {
    pair_iphone
    read -p "
    
1) Activate the iPhone. IMPORTANT: If you are going to use cellular features on iOS 9, your SIM card should be in the iPhone with an active carrier. 

2) Sign in to iCloud and complete Setup.app. Get to the home screen. 

3) Make sure Find My iPhone has been turned off.

After all of the above is true, press any key to continue..."

    wait_for_activation
}

is_activated() {

    if ideviceinfo 2>/dev/null | grep -q "^ActivationState: Activated$"; then
        return 0
    else
        return 1
    fi
}

start_rd() {
    # Enfore Recovery Mode.
    enter_recovery
    ssh_connected=0

    while [[ $ssh_connected != 1 ]]; do
        # Incase this failed previously and is running again, wait.
        wait_for_recovery
        # Stay in Recovery Mode, prevent normal mode booting until ramdisk boots and runs script to restore this. Unless we enter DFU mode accidentally this is the most useful case of enforce_recovery ever.
        enforce_recovery
        # Clear any existing iproxy...
        iproxy_kill
        # Attempt to boot ramdisk...
        (cd bin/Legacy-iOS-Kit && ./restore.sh --no-version-check --no-internet-check --sshrd-boot-rd-only)
        
        # Start our own proxy for USB SSH fresh...
        if [ "$os" = "Linux" ]; then
            usbmuxd_restart_polling > /dev/null 2>&1
        fi

        iproxy_kill
        iproxy_start
        echo "Waiting 5 seconds before testing SSH ramdisk connection, please standby..."
        sleep 5
        # SSH connection check.
        ssh_connected=$(sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1 'echo 1' 2>/dev/null)
    done

    # Need to reset this for ramdisk round 2.
    ssh_connected=0

    echo "Booted SSH Ramdisk!"

    #ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
}

wait_for_activation()
{
    # This confirms the iPhone is activated. It does not confirm if iCloud was signed in, if Find My iPhone was turned off, or if an active cell service SIM was used during activation.
    while ! is_activated; do
        read -p "iPhone is not activated! Please make sure all of the above criteria are true as well and then press enter."
        sleep 1
    done
}

got_all_activation_files() {
    if [[ -f data/"$device"_"$serial"/activate/activation_records.tar.gz && \
          -f data/"$device"_"$serial"/activate/data_ark.plist.tar.gz && \
          -f data/"$device"_"$serial"/activate/IC-Info.sisv.tar.gz && \
          -f data/"$device"_"$serial"/activate/com.apple.commcenter.device_specific_nobackup.plist.tar.gz && \
          -f data/"$device"_"$serial"/activate/com.apple.factorydata.tar.gz ]]; then
        return 0
    else
        mkdir -p data/"$device"_"$serial"/activate
        return 1
    fi
}

get_activation() {
    # Need to get activation files.
    echo -e "Existing activation files not backed up yet.\nObtaining activation files..."
    # Hail Mary if on latest iOS 15 already.
    ios_version=$(ideviceinfo 2>/dev/null | grep "ProductVersion" | awk '{print $2}')

    # Set $not_normal when first connecting/detecting iPhone if it is in Recovery or DFU Mode.
    if [ "$not_normal" = "true" ]; then
        echo "Your iPhone is not in normal mode, so iOS version can not be determined. Restoring iPhone to iOS 15.8.5."
        restore_signed_ios=true
    elif [ "$ios_version" != "15.8.5" ]; then
        echo "Latest iOS version is not installed. Restoring iPhone to iOS 15.8.5."
        restore_signed_ios=true
    elif [ "$ios_version" = "15.8.5" ]; then
        did_you_follow_instructions
    fi

    if [ "$restore_signed_ios" = "true" ]; then
        restore_signed_ios_for_device
    fi

    # Makes sure we don't stop until we actually get the activation files.
    while ! got_all_activation_files; do
        # Send it...
        start_rd

        expect <<EOF
        # Mount.
        spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
            }
        }

        expect "#"
        send "mount_filesystems\r"
        expect "#"
        
        # Ramdisk allows RW of / on unjailbroken iOS 15.8.5. on /private/var we have stable RO. RW sometimes doesn't work, so use / as scratch dir.
        send "mkdir /mnt1/activate\r"
        expect "#"
        
        # Copy activation_records.
        send "cp -a /mnt2/containers/Data/System/*/Library/activation_records /mnt1/activate/activation_records\r"
        expect "#"

        # Copy data_ark.plist.
        send "cp -a /mnt2/containers/Data/System/*/Library/activation_records/../internal/data_ark.plist /mnt1/activate\r"
        expect "#"

        # Copy IC-Info.sisv for notifications/ft/imessage/etc
        send "cp -a /mnt2/mobile/Library/FairPlay/iTunes_Control/iTunes/IC-Info.sisv /mnt1/activate\r"
        expect "#"

        # Copy com.apple.commcenter.device_specific_nobackup.plist
        send "cp -a /mnt2/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist /mnt1/activate\r"
        expect "#"
        
        # Copy com.apple.factorydata
        send "cp -a /mnt1/System/Library/Caches/com.apple.factorydata /mnt1/activate/com.apple.factorydata\r"
        expect "#"

        # Create tars.
        send "cd /mnt1/activate\r"
        expect "#"
        
        # activation_records.
        send "tar zcf activation_records.tar.gz activation_records\r"
        expect "#"

        # data_ark.plist.
        send "tar zcf data_ark.plist.tar.gz data_ark.plist\r"
        expect "#"
        send "rm data_ark.plist\r"
        expect "#"
        
        # IC-Info.sisv. 
        # Silence error: "tar: copyfile pack (IC-Info.sisv) failed: No such file or directory" because we still get the file fine.
        send "tar zcf IC-Info.sisv.tar.gz IC-Info.sisv > /dev/null 2>&1\r"
        expect "#"
        send "rm IC-Info.sisv\r"
        expect "#"

        # com.apple.commcenter.device_specific_nobackup.plist.
        send "tar zcf com.apple.commcenter.device_specific_nobackup.plist.tar.gz com.apple.commcenter.device_specific_nobackup.plist\r"
        expect "#"
        send "rm com.apple.commcenter.device_specific_nobackup.plist\r"
        expect "#"

        # com.apple.factorydata.
        send "tar zcf com.apple.factorydata.tar.gz com.apple.factorydata\r"
        expect "#"

        # Delete all directories.
        send "rm -rf */\r"
        expect "#"

        send "exit\r"
        expect eof

        # Transfer tars to computer.
        spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P 6414 root@127.0.0.1:/mnt1/activate "data/${device}_${serial}/"
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
                exp_continue
            }
            eof {
                puts "Transfer complete"
            }
        }

        # Unmount and Reboot.
        spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
            }
        }

        expect "#"
        send "reboot\r"
        expect "closed by remote host."
        expect eof
EOF

        iproxy_kill
        
        # Check to see if user follows instructions.  If not when we get back to restore_ipsw() it will prompt to go through get_activation() again.
        if ! got_all_activation_files; then
            echo "Error: not all activation files were backed up. Please make sure you complete all steps before activation files are backed up. A999 Activator will try getting activation files again."
            read -p "Press any key to continue..."
        fi
    done
}

downgrade() {    
    # Get Activation files.
    while ! got_all_activation_files; do
        get_activation
    done

    restore_ios_10_2_1_for_device
    # Enable all steps for final restore.
    not_final_restore=false
    restore_ipsw $1
    start_rd

    expect <<EOF
    # Set up /.
    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }

    expect "#"
    send "mount_hfs /dev/disk0s1s1 /mnt1\r"
    expect "#"
    send "mount_hfs /dev/disk0s1s2 /mnt2\r"
    expect "#"
    send "rm -rf /mnt1/activation\r"
    expect "#"
    send "mkdir /mnt1/Library/LaunchDaemons\r"
    expect "#"
    send "exit\r"
    expect eof

    # Transfer activation tars to phone.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P 6414 "data/${device}_${serial}/activate" root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Transfer launch daemon com.alex.activate.plist to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 payload/com.alex.activate.plist root@127.0.0.1:/mnt1/Library/LaunchDaemons
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Transfer activate script to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 payload/activate root@127.0.0.1:/mnt1/usr/bin
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Transfer freeze.tar to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/freeze.tar root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Transfer launchctl.tar to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/launchctl.tar root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Transfer io.pangu93.loader.plist to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/io.pangu93.loader.plist root@127.0.0.1:/mnt1/Library/LaunchDaemons
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
            exp_continue
        }
        eof {
            puts "Transfer complete"
        }
    }

    # Set permissions for activate.
    send "chmod 755 /mnt1/usr/bin/activate\r"
    expect "#"
    send "chown root:wheel /mnt1/usr/bin/activate\r"
    expect "#"

    # Install chflags from ramdisk
    send "cp -a /usr/bin/chflags /mnt1/usr/bin/chflags\r"
    expect "#"

    # Set permissions for launch daemon com.alex.activate.plist.
    expect "#"
    send "chmod 644 /mnt1/Library/LaunchDaemons/com.alex.activate.plist\r"
    expect "#"
    send "chown root:wheel /mnt1/Library/LaunchDaemons/com.alex.activate.plist\r"
    expect "#"
    
    # Move Setup.app to prevent possible deactivation causing it to trigger.
    send "mv /mnt1/Applications/Setup.app /mnt1/Applications/Setup.bak\r"
    expect "#"
    
    # BEGIN JAILBREAK BOOTSTRAP INSTALLATION.
    # Set permissions for launch daemon io.pangu93.loader.plist.
    send "chmod 644 /mnt1/Library/LaunchDaemons/io.pangu93.loader.plist \r"
    expect "#"
    send "chown root:wheel /mnt1/Library/LaunchDaemons/io.pangu93.loader.plist\r"
    expect "#"

    send "cd /mnt1\r"
    expect "#"

    # Extract freeze.tar.
    send "tar -xf freeze.tar -C .\r"
    expect "#"
    send "rm freeze.tar\r"
    expect "#"

    # Extract launchctl.tar.
    send "tar -xf launchctl.tar -C .\r"
    expect "#"
    send "rm launchctl.tar\r"
    expect "#"

    # Is this the symlink trick to write to /var?) 
    send "mv private/var/lib private\r"
    expect "#"
    send "mv private/var/mobile/Library/Preferences/com.apple.springboard.plist private\r"
    expect "#"
    send "rm -r private/var/*\r"
    expect "#"
    send "touch .cydia_no_stash\r"
    expect "#"
    send "cd /mnt2\r"
    expect "#"
    send "ln -s /private/lib\r"
    expect "#"
    send "cd mobile/Library/Preferences\r"
    expect "#"
    send "rm -f com.apple.springboard.plist\r"
    expect "#"
    send "ln -s /private/com.apple.springboard.plist\r"
    expect "#"
    send "chown 501:501 com.apple.springboard.plist\r"
    expect "#"
    send "exit\r"
    expect eof

    # Unmount and Reboot. Spawn a new session because symlink trick is weird and prevents unmounting /mnt2.
    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }

    expect "#"
    send "umount /mnt1\r"
    expect "#"
    send "umount /mnt2\r"
    expect "#"
    send "reboot\r"
    expect "closed by remote host."
    expect eof
EOF

    iproxy_kill
    boot_turdusra1n
    
    echo "Your iPhone is now jailbroken! You need to enable it now by visiting http://jbme.ddw.nu/ in Safari after signing in to your WiFi. Once the jailbreak is enabled, your iPhone will automatically reboot into Recovery Mode after restoring activation. Do not sign in to iCloud just yet! a999activator is going to start checking for Recovery Mode in 45 seconds so that the LAST STEP can be completed!"
    sleep 45

    boot_turdusra1n
    generate_boot_script
    echo "Activation was restored! You need to enable the jailbreak with http://jbme.ddw.nu in Safari everytime you boot, but your done!"
    echo "DO NOT SIGN IN TO ICLOUD IN SETUP.APP! It will not work. Instead, complete Setup.app without signing in and get to the home screen. Then, sign in to iCloud with the Settings app!"
    usbmuxd_restart
    echo -e "\nDONE!\n"
}

iphone_6s_firmware_select() {
    PS3="Select iOS version to downgrade to: "
    options=(
        "9.2 (13C75) (12/8/2015)"
        "9.2.1 (13D15) (1/19/2016)"
        #"9.2.1 (13D20) (2/18/2016)" Can't use because jbme doesn't support it
        "Exit"
    )

    select opt in "${options[@]}"
    do
        case $opt in
            "9.2 (13C75) (12/8/2015)")
                downgrade http://appldnld.apple.com/ios9.2/031-29220-20151203-557E81AA-8D8B-11E5-BEE6-AD638B8BECEB/iPhone8,1_9.2_13C75_Restore.ipsw
                break;
                ;;
            "9.2.1 (13D15) (1/19/2016)")
                downgrade http://appldnld.apple.com/ios9.2.1/031-47635-20160119-97350056-B969-11E5-A65F-634D8FD31F8F/iPhone8,1_9.2.1_13D15_Restore.ipsw
                break;
                ;;
            #"9.2.1 (13D20) (2/18/2016)") Can't use because jbme doesn't support it
                #downgrade http://appldnld.apple.com/ios9.2.1/031-49377-20160217-4BB1908C-D44D-11E5-9900-0952919DCAD8/iPhone8,1_9.2.1_13D20_Restore.ipsw
                #break;
                #;;
            "Exit")
                break
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}


iphone_6s_plus_firmware_select() {

    PS3="Select iOS version to downgrade to: "
    options=(
        "9.2 (13C75) (12/8/2015)"
        "9.2.1 (13D15) (1/19/2016)"
        #"9.2.1 (13D20) (2/18/2016)" can't use because jbme doesn't support it
        "Exit"
    )

    select opt in "${options[@]}"
    do
        case $opt in
            "9.2 (13C75) (12/8/2015)")
                downgrade http://appldnld.apple.com/ios9.2/031-29142-20151203-53B314A8-8D8B-11E5-B7FA-9A638B8BECEB/iPhone8,2_9.2_13C75_Restore.ipsw
                break;
                ;;
            "9.2.1 (13D15) (1/19/2016)")
                downgrade http://appldnld.apple.com/ios9.2.1/031-47609-20160119-798F784C-B969-11E5-8729-F24C8FD31F8F/iPhone8,2_9.2.1_13D15_Restore.ipsw
                break;
                ;;
            #"9.2.1 (13D20) (2/18/2016)") can't use because jbme doesn't support it
                #downgrade http://appldnld.apple.com/ios9.2.1/031-49073-20160217-4BB05046-D44D-11E5-9D30-0852919DCAD8/iPhone8,2_9.2.1_13D20_Restore.ipsw
                #break;
                #;;
            "Exit")
                break
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}

# Begin actual execution.

# Check for the existence of the binary launch daemon which is generated for the release by the build script.
if [ ! -f "payload/com.alex.activate.plist" ]; then
    echo "Error: can not find payload/com.alex.activate.plist. This most likely means you are trying to execute a999 from the source tree, rather then a release which is not allowed. Please execute the build command in the source tree and cd into the built release. If you downloaded an a999activator release and are getting this error, you release is incomplete and missing a neccesary file. Please redownload the release and run a999activator again."
    exit 1
fi

# Update functionallity. We need to get 2 things, the data folder and any boot* scripts.
if [ "$1" = "-u" ]; then
    if [ "$#" -ne 2 ]; then
        echo "You gave the -u argument, which expect an existing a999activator release directory as the following argument."
        exit 1
    fi

    update_existing_data "$2"
    exit 0
fi

startup
detect_iphone

if [ $device = "iphone_6s_plus" ]; then
    iphone_6s_plus_firmware_select
elif [ $device = "iphone_6s" ]; then
    iphone_6s_firmware_select
else
    echo "Error: only iPhone 6S and iPhone 6S Plus are supported by a999 activator."
    exit 1
fi
